apiVersion: apps/v1
kind: Deployment
metadata:
  name: ConvTemperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: fgajardo87/conversao-temperatura:v1
          ports:
            - containerPort: 80