apiVersion: apps/v1
kind: Deployment
metadata:
  name: convtemp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convtemp
  template:
    metadata:
      labels:
        app: convtemp
    spec:
      containers:
        - name: convtemp
          image: fgajardo87/conversao-temperatura:v1
          ports:
            - containerPort: 80